#!/bin/bash

maim -b 2 -s /tmp/screenshot.png

if [[ $? -eq 0 ]]; then
	text=$(tesseract /tmp/screenshot.png stdout)
	notify-send -a snapcopy "Copied: $text"
	xdg-open "https://duckduckgo.com/?q=$(echo $text | sed 's/ /+/g')"
else
	notify-send -a snapcopy "Selection cancelled."
fi
